### ISSUE TITLE
All versions of the IDE should use the native (not the built_in) ssh executable for git

### ISSUE THREAD

**Issue by codeword** [pivotal/pivotal_ide_prefs#14]
In order to accomplish this we need to change the SSH_EXECUTABLE option from 'IDEA_SSH' to 'NATIVE_SSH' inside the options/git.xml preference file 

This file is not currently managed by this project.

**Comment by moonmaster9000** [comment]
Hi! Thanks for raising the issue. Can you explain why all versions of the IDE should use the native (not the built_in) ssh executable for git?
