### ISSUE TITLE
RubyMine displays "Cannot parse first-keystroke.." error on startup

### ISSUE THREAD

**Issue by aramprice** [pivotal/pivotal_ide_prefs#24]
We are using pivotal/pivotal_ide_prefs via pivotal-sprout/sprout-jetbrains-editors and were able to reproduce this after removing the pivotal/pivotal_ide_prefs locally and re-running the pivotal-sprout/sprout-jetbrains-editors cookbook.

This error appears on RubyMine startup:

> Cannot read scheme Pivotal Common.xml from '$ROOT_CONFIG$/keymaps': Cannot parse first-keystroke: 'ctrl meta alt open_bracket'; Action's id=EditorMatchBrace; Keymap's name=Pivotal Common

![rubymine-error](https://cloud.githubusercontent.com/assets/12226/10107123/ba46f2cc-636d-11e5-99a9-a1759d614247.png)

**Comment by moonmaster9000** [comment]
Sorry, should now be fixed on master. Apparently that keymap works great in
intellij but not in Rubymine. Apologies! I'll work with the original
committer of that keymap to get it sorted.

On Fri, Sep 25, 2015 at 1:14 PM, aram price <notifications@github.com>
wrote:

> We are using pivotal/pivotal_ide_prefs via
> pivotal-sprout/sprout-jetbrains-editors and were able to reproduce this
> after removing the pivotal/pivotal_ide_prefs locally and re-running the
> pivotal-sprout/sprout-jetbrains-editors cookbook.
>
> Cannot read scheme Pivotal Common.xml from '$ROOT_CONFIG$/keymaps': Cannot
> parse first-keystroke: 'ctrl meta alt open_bracket'; Action's
> id=EditorMatchBrace; Keymap's name=Pivotal Common
>
> [image: rubymine-error]
> <https://cloud.githubusercontent.com/assets/12226/10107123/ba46f2cc-636d-11e5-99a9-a1759d614247.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pivotal/pivotal_ide_prefs/issues/24>.
>



-- 
Parker Matthew
Associate Director of Engineering
Pivotal Labs, NY
mparker@pivotal.io

**Comment by moonmaster9000** [comment]
OK, now it should really be fixed on master. The culprit was this commit: https://github.com/pivotal/pivotal_ide_prefs/commit/d99c0de30cdcf26712a4c2f7417c4cd68ce212a3

Intellij 14 is apparently downcasing things in the config files, but RubyMine latest doesn't yet understand that. Fun times.

**Comment by aramprice** [comment]
Thanks for the quick turn around, things looking good in sprout-land
