### ISSUE TITLE
Documentation for keymappings?

### ISSUE THREAD

**Issue by bwheeler96** [pivotal/pivotal_ide_prefs#27]
I was wondering if there's documentation for the keymappings somewhere, or if there will be in the future?

**Comment by moonmaster9000** [comment]
Hi Brian!

Unfortunately there's no documentation; I would happily accept a pull
request that generates documentation from the XML files, though!

On Fri, Oct 16, 2015 at 1:49 PM, Brian Wheeler <notifications@github.com>
wrote:

> I was wondering if there's documentation for the keymappings somewhere, or
> if there will be in the future?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pivotal/pivotal_ide_prefs/issues/27>.
>



-- 
Parker Matthew
Associate Director of Engineering
Pivotal Labs, NY
mparker@pivotal.io
