### ISSUE TITLE
Keymaps on webstorm occasionally reset

### ISSUE THREAD

**Issue by atomanyih** [pivotal/pivotal_ide_prefs#29]
Dear parks,

It seems like the Pivotal Common parent is deleted or somehow disappears. Pivotal Webstorm is still available, but it has no bindings. 

Uninstalling and reinstalling fixes, but it makes me sad

Seeing this happen consistently on one computer.
Will update with more info as I discover it, and fix it if I can.

best,
August

**Comment by moonmaster9000** [comment]
wow bummer... I'm guessing this has started happening with the latest
version of webstorm? I wonder if it eventually decides that it dislikes
symlinks.

On Mon, Dec 14, 2015 at 1:41 PM, August Toman-Yih <notifications@github.com>
wrote:

> Dear parks,
>
> It seems like the Pivotal Common parent is deleted or somehow disappears.
> Pivotal Webstorm is still available, but it has no bindings.
>
> Uninstalling and reinstalling fixes, but it makes me sad
>
> Seeing this happen consistently on one computer.
> Will update with more info as I discover it, and fix it if I can.
>
> best,
> August
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pivotal/pivotal_ide_prefs/issues/29>.
>



-- 
Parker Matthew
Associate Director of Engineering
Pivotal Labs, NY
mparker@pivotal.io

**Comment by atomanyih** [comment]
I'm not sure. Our other station is not having this problem, but I have a vague memory of switching to `Pivotal Common` instead of `Pivotal Webstorm`. Maybe it doesn't delete the active keymap?
