### ISSUE TITLE
Provide keyboard mappings for linux (ubuntu)

### ISSUE THREAD

**Issue by jadekler** [pivotal/pivotal_ide_prefs#34]
The denver office is experimenting with using ubuntu instead of mac. Would it be feasible for this repo to provide the same set of keyboard shortcuts for ubuntu as we get for macs? At the moment the `bin/cli` runs successfully but has no impact on intellij's settings (presumably putting files in a place that ubuntu intellij doesnt care about).

**Comment by moonmaster9000** [comment]
Hi!

Have you tried the --user-prefs-location=PATH command line option?

**Comment by moonmaster9000** [comment]
By default, pivotal_ide_prefs installs to ~/Library/Preferences/<IDE><VERSION> (which is the location that the JetBrains IDEs store prefs on Macs). However, you can override that default with the --user-prefs-location=PATH command line option. Something like: 

`
$ bin/ide_prefs --install --user-prefs-location=/some/path --ide=<SOMEIDE>
`

**Comment by moonmaster9000** [comment]
(Also, sorry I didn't see your issue 5 days ago when you posted it! I'm not sure how I missed it. Please forgive my belated reply).

**Comment by jadekler** [comment]
@moonmaster9000 Thanks for the reply! I'll give it a shot and report back

**Comment by moonmaster9000** [comment]
Hi! Closing this issue for now. If you ran into any issues, please feel free to reopen an issue. Thanks!
