### ISSUE TITLE
CLion support?

### ISSUE THREAD

**Issue by d** [pivotal/pivotal_ide_prefs#40]
Are we open to adding CLion support? I might have time to work on that

**Comment by moonmaster9000** [comment]
Of course, please do add it! Should be a cinch since it's a jetbrains
product. The README has instructions on how to add prefs for editors, or
just look at previous commits that added support for jetbrains editors.

**Comment by moonmaster9000** [comment]
CLion support is now in there thanks to pull requests from the Professor (Todd Sedano)
