### ISSUE TITLE
Pref source for IntelliJ Ultimate is broken

### ISSUE THREAD

**Issue by ericTsiliacos** [pivotal/pivotal_ide_prefs#55]
If you look at pref_sources/IntelliJ/keymaps/Pivotal IntelliJ.xml, you'll see that the <keymap> element is missing an attribute. Specifically, it should have ```parent="Pivotal Common"```.

Thanks,
Eric

**Comment by moonmaster9000** [comment]
Hi Eric,

I see that you closed this shortly after opening, so I'm guessing that you
discovered this is a duplicate of a known issue, but just in case:
Jetbrains broke custom pref files in their 2016.3 releases; they've already
fixed it for all of their 2017.1 releases; we recommend you download the
2017.1 EAP releases for now, until the 2017.1 releases go GA.
