### ISSUE TITLE
XML files always show modified after opening IDE

### ISSUE THREAD

**Issue by thewoolleyman** [pivotal/pivotal_ide_prefs#59]
The way the XML files are currently saved in the repo is different than the way Jetbrains likes to save the XML files.

E.g., doctype line, newline at end of file, alphabetizing of elements, etc.

This results in the repo always showing modified files (since the actual files are symlinked into the repo), and difficult to know what changes have actually been made and need to be committed.

Would you accept a PR that cleans this up, and makes every XML file match what Jetbrains saves it as?

**Comment by moonmaster9000** [comment]
Yes, happy to accept it; warning though: this seems to happen with pretty
much every release of jet brains IDEs, people have submitted PRs in the
past only to have new releases cause the same reformatting again.
